name: Gitlab Mirror

on: push

jobs:
  do_mirror:
    runs-on: ubuntu-latest
    steps:
        - uses: actions/checkout@v6
          with:
            fetch-depth: 0
        - uses: yesolutions/mirror-action@v0.7.0
        with:
          REMOTE: 'https://gitlab.osti.gov/genesis/lcf-inference-scaling.git/'
          GIT_USERNAME: raffenet
          GIT_PASSWORD: ${{ secrets.OSTI_GITLAB_TOKEN }}
